class AppLocalizations {
  final String languageCode;

  const AppLocalizations(this.languageCode);

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'id', 'name': 'Bahasa Indonesia', 'flag': '🇮🇩'},
    {'code': 'en', 'name': 'English', 'flag': '🇺🇸'},
    {'code': 'ja', 'name': '日本語 (Japanese)', 'flag': '🇯🇵'},
    {'code': 'zh_CN', 'name': '简体中文 (China)', 'flag': '🇨🇳'},
    {'code': 'zh_TW', 'name': '繁體中文 (Taiwan)', 'flag': '🇹🇼'},
    {'code': 'ko', 'name': '한국어 (Korean)', 'flag': '🇰🇷'},
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      'desc_crf': 'Mempertahankan kualitas visual yang konsisten tanpa memedulikan ukuran akhir file. Semakin kecil angkanya, semakin tinggi kualitasnya namun ukurannya semakin besar. Sangat direkomendasikan.',
      'desc_bitrate': 'Memaksa video untuk mencapai ukuran target MB yang pasti, kualitas visual akan menyesuaikan.',
      'desc_mp4': 'Ringan dan universal. Media Sosial, Rekaman HP, Berbagi video.',
      'desc_mkv': 'Banyak audio & subtitle dalam 1 file. Menyimpan Film, Anime, Seri TV.',
      'desc_mov': 'Kualitas visual mentah (tinggi). Editing Video Profesional (Premiere/FCPX).',
      'desc_webm': 'Mendukung video transparan. Animasi Web, Konten Streaming Online.',
      'desc_h264': 'Live Streaming, Video Web, Rekaman HP standar. Kompatibilitas Luar Biasa.',
      'desc_hevc': 'Streaming 4K, Film Kualitas Tinggi. Efisiensi Kompresi Sangat Tinggi.',
      'desc_vp9': 'YouTube, Google Products. Efisiensi Kompresi Sangat Tinggi.',
      'est_size_title': 'Estimasi Ukuran Output:',
      'est_size_warning': '* Ukuran asli dapat bervariasi bergantung tingkat kerumitan visual video.',
      'crf_label': 'Nilai CRF (Lebih kecil = Kualitas makin baik, Ukuran makin besar)',
      'bitrate_label': 'Target Bitrate (Mbps)',
      'app_title': 'Phantek Video Toolkit',
      'app_tagline': 'Konversi video 4K/2K ke resolusi\nyang lebih kecil dengan mudah',
      'pick_video': 'Pilih Video',
      'change_video': 'Ganti Video',
      'reset': 'Reset',
      'settings': 'Pengaturan',
      'loading_pick': 'Mempersiapkan pemilihan video...',
      'loading_analyzing': 'Menganalisis & memuat info video...',
      'loading_large_hint': 'Video berukuran besar membutuhkan beberapa detik untuk dianalisis.',
      'error_read_video': 'Gagal membaca informasi video',
      'source_video': 'Video Sumber',
      'resolution': 'Resolusi',
      'duration': 'Durasi',
      'bitrate': 'Bitrate',
      'file_size': 'Ukuran',
      'fps': 'FPS',
      'codec': 'Codec',
      'format': 'Format',
      'target_resolution': 'Target Resolusi',
      'original_resolution': 'Asli (Sama dengan sumber)',
      'video_already_low': 'Video sudah beresolusi rendah',
      'can_still_compress': 'Anda masih bisa mengompresi bitrate atau mengubah format/codec.',
      'video_options': 'Opsi Video & Kompresi',
      'bitrate_setting': 'Target Bitrate',
      'container_format': 'Format Kontainer',
      'video_codec': 'Codec Video',
      'start_conversion': 'Mulai Konversi',
      'feature_downscale': '4K → 1080p',
      'feature_fast': 'Cepat',
      'feature_quality': 'Berkualitas',
      'feature_offline': '100% Offline',
      'settings_title': 'Pengaturan',
      'settings_language': 'Bahasa / Language',
      'settings_language_desc': 'Pilih bahasa tampilan antarmuka aplikasi.',
      'settings_theme': 'Tema Tampilan',
      'settings_theme_desc': 'Pilih antara Mode Gelap standar, Mode Gelap OLED hemat daya untuk layar AMOLED, atau Mode Terang.',
      'theme_dark': 'Mode Gelap',
      'theme_oled': 'Dark OLED',
      'theme_light': 'Mode Terang',
      'settings_wakelock': 'Cegah Layar Mati',
      'settings_wakelock_desc': 'Mencegah layar HP mati/tertidur saat aplikasi sedang berjalan atau mengonversi video. ⚠️ Peringatan: Fitur ini akan mengonsumsi daya baterai lebih cepat.',
      'settings_hardware': 'Perangkat Keras & Performa',
      'settings_cpu_threads': 'Penggunaan Core CPU / Thread',
      'settings_cpu_threads_desc': 'Tentukan jumlah thread encoding. Semakin banyak core, semakin cepat proses konversi.',
      'settings_detected_cores': 'Terdeteksi {count} Core pada perangkat ini',
      'settings_auto_cores': 'Auto (Semua Core)',
      'settings_ram_buffer': 'Batas RAM & Buffer Memori',
      'settings_ram_buffer_desc': 'Mengatur batas alokasi buffer caching FFmpeg untuk mencegah force close (OOM).',
      'settings_ram_low': '256 MB (Hemat Memori)',
      'settings_ram_standard': '512 MB (Standar / Seimbang)',
      'settings_ram_high': '1024 MB (Performa Tinggi)',
      'settings_ram_max': '2048 MB (Maksimum)',
      'settings_cpu_preset': 'Preset Kecepatan CPU (Preset)',
      'settings_cpu_preset_desc': 'Fast: proses cepat tanpa kompresi berat; Normal: seimbang antara kecepatan & ukuran; Slow: memaksimalkan kompresi (proses lambat).',
      'preset_fast': 'Fast (Tanpa Kompres)',
      'preset_normal': 'Normal (Balance)',
      'preset_slow': 'Slow (Maksimal Kompresi)',
      'settings_hw_accel': 'Akselerasi Perangkat Keras (Eksperimental)',
      'settings_hw_accel_desc': 'Gunakan MediaCodec bawaan Android untuk proses yang lebih hemat daya jika didukung chip.',
      'settings_audio_quality': 'Kualitas Audio',
      'settings_audio_quality_desc': 'Mengatur bitrate audio AAC atau pilih hening untuk menghapus suara agar ukuran file semakin kecil.',
      'settings_audio_mute': 'Hening (Tanpa Suara)',
      'settings_reset_default': 'Kembalikan Pengaturan Default',
      'settings_reset_confirm_title': 'Reset Pengaturan?',
      'settings_reset_confirm_desc': 'Apakah Anda yakin ingin mengembalikan semua preferensi ke pengaturan bawaan?',
      'settings_reset_success': 'Pengaturan berhasil direset ke default',
      'settings_about': 'Tentang Aplikasi',
      'settings_about_desc': 'Phantek Video Toolkit adalah aplikasi open-source untuk kompresi dan konversi video secara aman dan 100% offline tanpa mengunggah ke internet.',
      'bitrate_auto': 'Auto (Dihitung Otomatis)',
      'bitrate_high': 'Kualitas Tinggi',
      'bitrate_medium': 'Seimbang',
      'bitrate_low': 'Hemat Ukuran (Terkecil)',
      'bitrate_custom': 'Kustom ({value} kbps)',
      'proc_title': 'Proses Konversi',
      'proc_preparing': 'Mempersiapkan konversi...',
      'proc_converting': 'Mengkonversi video...',
      'proc_completed': 'Selesai!',
      'proc_failed': 'Gagal mengkonversi video',
      'proc_open_file': 'Buka File Video',
      'proc_back': 'Kembali',
      'proc_retry': 'Coba Lagi',
      'proc_cancel': 'Batalkan',
      'proc_cancel_title': 'Batalkan Konversi?',
      'proc_cancel_desc': 'Proses encoding sedang berjalan. Apakah Anda yakin ingin menghentikannya?',
      'proc_yes_cancel': 'Ya, Batalkan',
      'proc_no': 'Lanjutkan',
      'proc_source': 'Sumber',
      'proc_target': 'Target',
      'proc_output_size': 'Ukuran Output',
      'proc_savings': 'Hemat {percent}%',
      'proc_size_increase': 'Ukuran +{percent}%',
      'proc_savings_title': 'Hemat Storage: {percent}%',
      'proc_size_increase_title': 'Ukuran Bertambah: +{percent}%',
      'proc_size_increase_hint': 'Ukuran hasil konversi lebih besar dari video asli untuk menjaga kualitas visual maksimal.',
      'proc_elapsed_time': 'Waktu Berjalan',
      'proc_remaining_time': 'Estimasi Selesai',
      'proc_calculating': 'Menghitung...',
      'proc_total_time': 'Selesai dalam {time}',
      'proc_saved_location': 'Folder Penyimpanan',
      'proc_saved_path': 'Movies',
      'settings_storage': 'Penyimpanan & Cache',
      'settings_storage_desc': 'Kelola file cache sementara untuk mencegah aplikasi menggunakan ruang penyimpanan berlebih.',
      'settings_cache_size': 'Ukuran Cache Saat Ini',
      'settings_clear_cache': 'Bersihkan Cache Sekarang',
      'settings_clear_cache_success': 'Cache berhasil dibersihkan! {size} ruang dibebaskan.',
      'settings_cache_info': 'Pembersihan Otomatis Aktif',
      'settings_cache_info_desc': 'Salinan video sementara dari pemilih file otomatis dihapus setelah konversi selesai.',
      'device_specs': 'Spesifikasi Perangkat',
      'device_model': 'Model',
      'device_soc': 'SoC / Board',
      'device_cpu_cores': 'Core CPU',
      'device_total_ram': 'Total RAM',
      'theme_dark_desc': 'Navy / Slate Gelap (#11111B)',
      'theme_oled_desc': 'Hitam Pekat (#000000) • Hemat baterai AMOLED',
      'theme_light_desc': 'Bersih & Terang (#F6F7FB)',
      'select_mode': 'Pilih Mode',
      'mode_downscale': 'Downscale',
      'mode_upscale': 'Upscale',
      'mode_convert': 'Konversi',
      'badge_soon': 'Segera',
      'target_fps': 'Target FPS',
      'fps_original': 'Asli',
      'proc_play_video': 'Buka / Mainkan',
      'share': 'Bagikan',
      'close': 'Tutup',
      'no_downscale_options': 'Video sudah berada di resolusi rendah.\nTidak ada opsi downscale tersedia.',
      'proc_notif_completed': 'Konversi Selesai! Video disimpan di Movies',
    },
    'en': {
      'desc_crf': 'Maintains consistent visual quality regardless of final file size. Lower value means better quality but larger size. Highly recommended.',
      'desc_bitrate': 'Forces the video to meet an exact target MB size, visual quality will adjust accordingly.',
      'desc_mp4': 'Lightweight and universal. Social Media, Phone Recordings, Video sharing.',
      'desc_mkv': 'Multiple audio & subtitles in 1 file. Movies, Anime, TV Series.',
      'desc_mov': 'High visual raw quality. Professional Video Editing (Premiere/FCPX).',
      'desc_webm': 'Supports transparent video. Web Animation, Online Streaming Content.',
      'desc_h264': 'Live Streaming, Web Video, Standard Phone recordings. Excellent Compatibility.',
      'desc_hevc': '4K Streaming, High Quality Movies. Very High Compression Efficiency.',
      'desc_vp9': 'YouTube, Google Products. Very High Compression Efficiency.',
      'est_size_title': 'Estimated Output Size:',
      'est_size_warning': '* Actual size may vary depending on the visual complexity of the video.',
      'crf_label': 'CRF Value (Lower = Better Quality, Larger Size)',
      'bitrate_label': 'Target Bitrate (Mbps)',
      'app_title': 'Phantek Video Toolkit',
      'app_tagline': 'Downscale & compress 4K/2K videos\nto smaller resolutions effortlessly',
      'pick_video': 'Select Video',
      'change_video': 'Change Video',
      'reset': 'Reset',
      'settings': 'Settings',
      'loading_pick': 'Preparing file picker...',
      'loading_analyzing': 'Analyzing & probing video info...',
      'loading_large_hint': 'Large video files may take several seconds to analyze.',
      'error_read_video': 'Failed to read video information',
      'source_video': 'Source Video',
      'resolution': 'Resolution',
      'duration': 'Duration',
      'bitrate': 'Bitrate',
      'file_size': 'Size',
      'fps': 'FPS',
      'codec': 'Codec',
      'format': 'Format',
      'target_resolution': 'Target Resolution',
      'original_resolution': 'Original (Same as source)',
      'video_already_low': 'Video already has low resolution',
      'can_still_compress': 'You can still re-encode bitrate or change format/codec.',
      'video_options': 'Video & Compression Options',
      'bitrate_setting': 'Target Bitrate',
      'container_format': 'Container Format',
      'video_codec': 'Video Codec',
      'start_conversion': 'Start Conversion',
      'feature_downscale': '4K → 1080p',
      'feature_fast': 'Fast',
      'feature_quality': 'High Quality',
      'feature_offline': '100% Offline',
      'settings_title': 'Settings',
      'settings_language': 'Language',
      'settings_language_desc': 'Select your preferred user interface language.',
      'settings_theme': 'Theme Appearance',
      'settings_theme_desc': 'Choose between Standard Dark mode, battery-saving OLED Dark mode for AMOLED screens, or Light mode.',
      'theme_dark': 'Dark Mode',
      'theme_oled': 'Dark OLED',
      'theme_light': 'Light Mode',
      'settings_wakelock': 'Keep Screen Awake',
      'settings_wakelock_desc': 'Prevent the display from turning off or sleeping while using the app or encoding videos. ⚠️ Warning: This feature will consume battery power faster.',
      'settings_hardware': 'Hardware & Performance',
      'settings_cpu_threads': 'CPU Cores / Threads',
      'settings_cpu_threads_desc': 'Configure encoding thread count. More cores increase conversion speed.',
      'settings_detected_cores': 'Detected {count} Cores on this device',
      'settings_auto_cores': 'Auto (All Cores)',
      'settings_ram_buffer': 'RAM & Memory Buffer Limit',
      'settings_ram_buffer_desc': 'Controls FFmpeg memory caching buffer size to prevent out-of-memory crashes.',
      'settings_ram_low': '256 MB (Low Memory)',
      'settings_ram_standard': '512 MB (Balanced)',
      'settings_ram_high': '1024 MB (High Performance)',
      'settings_ram_max': '2048 MB (Maximum)',
      'settings_cpu_preset': 'Encoding Speed Preset (x264/x265)',
      'settings_cpu_preset_desc': 'Fast: rapid encoding with minimal compression; Normal: balanced speed & file size; Slow: maximizes compression (slower process).',
      'preset_fast': 'Fast (No Compress)',
      'preset_normal': 'Normal (Balanced)',
      'preset_slow': 'Slow (Max Compress)',
      'settings_hw_accel': 'Hardware Acceleration (Experimental)',
      'settings_hw_accel_desc': 'Utilize Android MediaCodec for power-efficient encoding if supported by hardware.',
      'settings_audio_quality': 'Audio Quality',
      'settings_audio_quality_desc': 'Configure output AAC audio bitrate or select Mute to strip audio tracks for smaller files.',
      'settings_audio_mute': 'Mute (No Audio)',
      'settings_reset_default': 'Reset to Default Settings',
      'settings_reset_confirm_title': 'Reset Settings?',
      'settings_reset_confirm_desc': 'Are you sure you want to restore all settings to default values?',
      'settings_reset_success': 'Settings successfully restored to default',
      'settings_about': 'About App',
      'settings_about_desc': 'Phantek Video Toolkit is a 100% offline, privacy-first mobile transcoding tool powered by FFmpeg.',
      'bitrate_auto': 'Auto (Calculated)',
      'bitrate_high': 'High Quality',
      'bitrate_medium': 'Balanced',
      'bitrate_low': 'Smallest File Size',
      'bitrate_custom': 'Custom ({value} kbps)',
      'proc_title': 'Conversion Process',
      'proc_preparing': 'Preparing conversion...',
      'proc_converting': 'Converting video...',
      'proc_completed': 'Completed!',
      'proc_failed': 'Video conversion failed',
      'proc_open_file': 'Open Video File',
      'proc_back': 'Back',
      'proc_retry': 'Try Again',
      'proc_cancel': 'Cancel',
      'proc_cancel_title': 'Cancel Conversion?',
      'proc_cancel_desc': 'Video encoding is currently in progress. Are you sure you want to cancel?',
      'proc_yes_cancel': 'Yes, Cancel',
      'proc_no': 'Continue',
      'proc_source': 'Source',
      'proc_target': 'Target',
      'proc_output_size': 'Output Size',
      'proc_savings': 'Saved {percent}%',
      'proc_size_increase': 'Size +{percent}%',
      'proc_savings_title': 'Storage Saved: {percent}%',
      'proc_size_increase_title': 'File Size Increased: +{percent}%',
      'proc_size_increase_hint': 'Converted file is larger than original to maintain maximum visual quality.',
      'proc_elapsed_time': 'Elapsed Time',
      'proc_remaining_time': 'Estimated Remaining',
      'proc_calculating': 'Calculating...',
      'proc_total_time': 'Completed in {time}',
      'proc_saved_location': 'Storage Folder',
      'proc_saved_path': 'Movies',
      'settings_storage': 'Storage & Cache',
      'settings_storage_desc': 'Manage temporary cache files to prevent excessive app storage usage.',
      'settings_cache_size': 'Current Cache Size',
      'settings_clear_cache': 'Clear Cache Now',
      'settings_clear_cache_success': 'Cache cleared successfully! {size} freed.',
      'settings_cache_info': 'Auto-cleanup Active',
      'settings_cache_info_desc': 'Temporary video copies from file picker are automatically deleted after conversion.',
      'device_specs': 'Device Specifications',
      'device_model': 'Model',
      'device_soc': 'SoC / Board',
      'device_cpu_cores': 'CPU Cores',
      'device_total_ram': 'Total RAM',
      'theme_dark_desc': 'Navy / Slate Dark (#11111B)',
      'theme_oled_desc': 'True Black (#000000) • AMOLED battery saver',
      'theme_light_desc': 'Clean & Bright (#F6F7FB)',
      'select_mode': 'Select Mode',
      'mode_downscale': 'Downscale',
      'mode_upscale': 'Upscale',
      'mode_convert': 'Convert',
      'badge_soon': 'Soon',
      'target_fps': 'Target FPS',
      'fps_original': 'Original',
      'proc_play_video': 'Open / Play Video',
      'share': 'Share',
      'close': 'Close',
      'no_downscale_options': 'Video is already at a low resolution.\nNo downscale options available.',
      'proc_notif_completed': 'Conversion Completed! Video saved to Movies',
    },
    'ja': {
      'desc_crf': '最終ファイルサイズに関係なく一定の画質を維持します。数値が小さいほど高画質になりますが、サイズが大きくなります。強く推奨されます。',
      'desc_bitrate': '指定した目標サイズ（MB）に正確に収まるようにビットレートを固定します。画質は自動調整されます。',
      'desc_mp4': '軽量で最も高い互換性。SNS、スマホ撮影、動画共有に最適。',
      'desc_mkv': '1つのファイルに複数の音声や字幕を保持可能。映画、アニメ、TV番組向け。',
      'desc_mov': '非圧縮に近い高画質。PremiereやFCPXなどの動画編集向け。',
      'desc_webm': '透明動画に対応。Webアニメーションやオンライン配信コンテンツ向け。',
      'desc_h264': 'ライブ配信、Web動画、スマホ撮影の標準規格。非常に優れた互換性。',
      'desc_hevc': '4K配信、高画質映画。非常に高い圧縮効率で容量を約半分に削減。',
      'desc_vp9': 'YouTubeやGoogle製品で広く採用。非常に高い圧縮効率。',
      'est_size_title': '推定出力サイズ:',
      'est_size_warning': '* 実際のサイズは映像の複雑さや動きにより異なる場合があります。',
      'crf_label': 'CRF値 (小さい = 高画質・大サイズ)',
      'bitrate_label': '目標ビットレート (Mbps)',
      'app_title': 'Phantek Video Toolkit',
      'app_tagline': '4K/2K動画を高画質のまま\n手軽に縮小・圧縮します',
      'pick_video': '動画を選択',
      'change_video': '別の動画を選択',
      'reset': 'リセット',
      'settings': '設定',
      'loading_pick': 'ファイルピッカーを起動中...',
      'loading_analyzing': '動画情報を解析中...',
      'loading_large_hint': '大容量の動画ファイルは読み込みに数秒かかる場合があります。',
      'error_read_video': '動画情報の読み取りに失敗しました',
      'source_video': '元の動画',
      'resolution': '解像度',
      'duration': '再生時間',
      'bitrate': 'ビットレート',
      'file_size': 'ファイルサイズ',
      'fps': 'フレームレート',
      'codec': 'コーデック',
      'format': 'フォーマット',
      'target_resolution': '目標解像度',
      'original_resolution': '元と同じ解像度',
      'video_already_low': 'すでに低解像度の動画です',
      'can_still_compress': 'ビットレート圧縮や形式/コーデック変換は可能です。',
      'video_options': '動画・圧縮オプション',
      'bitrate_setting': '目標ビットレート',
      'container_format': 'コンテナ形式',
      'video_codec': '動画コーデック',
      'start_conversion': '変換を開始',
      'feature_downscale': '4K → 1080p',
      'feature_fast': '高速処理',
      'feature_quality': '高画質',
      'feature_offline': '完全オフライン',
      'settings_title': '設定',
      'settings_language': '言語 (Language)',
      'settings_language_desc': 'アプリの表示言語を選択します。',
      'settings_theme': 'テーマ設定',
      'settings_theme_desc': '標準のダークモード、AMOLED画面で省電力なOLEDダークモード、またはライトモードを選択します。',
      'theme_dark': 'ダークモード',
      'theme_oled': 'OLED ダーク',
      'theme_light': 'ライトモード',
      'settings_wakelock': '画面スリープ防止',
      'settings_wakelock_desc': '動画の変換中やアプリ使用中に画面がスリープするのを防ぎます。⚠️ 警告: この機能を有効にするとバッテリーの消費が早くなります。',
      'settings_hardware': 'ハードウェア・パフォーマンス',
      'settings_cpu_threads': 'CPUコア数 / スレッド数',
      'settings_cpu_threads_desc': 'エンコードに使用するスレッド数を指定します。コア数が多いほど高速に変換できます。',
      'settings_detected_cores': 'この端末で {count} 個のCPUコアを検出',
      'settings_auto_cores': '自動 (全コア使用)',
      'settings_ram_buffer': 'RAM・メモリバッファ制限',
      'settings_ram_buffer_desc': 'メモリ不足(OOM)を防ぐためのFFmpegキャッシュメモリバッファサイズを設定します。',
      'settings_ram_low': '256 MB (省メモリ)',
      'settings_ram_standard': '512 MB (標準・バランス)',
      'settings_ram_high': '1024 MB (高性能)',
      'settings_ram_max': '2048 MB (最大)',
      'settings_cpu_preset': 'エンコード速度プリセット',
      'settings_cpu_preset_desc': 'Fast：高速処理（低圧縮）；Normal：速度とサイズのバランス；Slow：最大圧縮（低速）。',
      'preset_fast': 'Fast (無圧縮・高速)',
      'preset_normal': 'Normal (バランス)',
      'preset_slow': 'Slow (最大圧縮)',
      'settings_hw_accel': 'ハードウェアアクセラレーション (実験的)',
      'settings_hw_accel_desc': '対応している場合、Android MediaCodecで省電力エンコードを行います。',
      'settings_audio_quality': '音質 (ビットレート)',
      'settings_audio_quality_desc': 'AAC音声ビットレートを設定します。無音を選択すると音声トラックを削除して容量を節約できます。',
      'settings_audio_mute': 'ミュート (無音)',
      'settings_reset_default': '初期設定に戻す',
      'settings_reset_confirm_title': '設定を初期化しますか？',
      'settings_reset_confirm_desc': 'すべての設定をデフォルト値に戻してもよろしいですか？',
      'settings_reset_success': '設定をデフォルトに戻しました',
      'settings_about': 'アプリについて',
      'settings_about_desc': 'Phantek Video Toolkitは、完全オフラインで動作する安心の動画縮小・圧縮アプリです。',
      'bitrate_auto': '自動 (推奨)',
      'bitrate_high': '高画質',
      'bitrate_medium': 'バランス',
      'bitrate_low': '容量優先 (最小)',
      'bitrate_custom': 'カスタム ({value} kbps)',
      'proc_title': '変換処理',
      'proc_preparing': '変換を準備中...',
      'proc_converting': '動画を変換中...',
      'proc_completed': '完了！',
      'proc_failed': '動画の変換に失敗しました',
      'proc_open_file': '動画ファイルを開く',
      'proc_back': '戻る',
      'proc_retry': '再試行',
      'proc_cancel': 'キャンセル',
      'proc_cancel_title': '変換を中止しますか？',
      'proc_cancel_desc': '現在動画のエンコード処理中です。中止してもよろしいですか？',
      'proc_yes_cancel': 'はい、中止します',
      'proc_no': '続ける',
      'proc_source': '元動画',
      'proc_target': '変換後',
      'proc_output_size': '出力サイズ',
      'proc_savings': '{percent}% 節約',
      'proc_size_increase': 'サイズ +{percent}%',
      'proc_savings_title': 'ストレージ節約: {percent}%',
      'proc_size_increase_title': 'ファイルサイズ増加: +{percent}%',
      'proc_size_increase_hint': '最高の画質を維持するため、変換後のファイルサイズが元の動画より大きくなっています。',
      'proc_elapsed_time': '経過時間',
      'proc_remaining_time': '残り予定時間',
      'proc_calculating': '計算中...',
      'proc_total_time': '所要時間: {time}',
      'proc_saved_location': '保存フォルダー',
      'proc_saved_path': 'Movies',
      'settings_storage': 'ストレージとキャッシュ',
      'settings_storage_desc': '一時ファイルを管理して端末のストレージを解放します。',
      'settings_cache_size': '現在のキャッシュサイズ',
      'settings_clear_cache': 'キャッシュを今すぐ消去',
      'settings_clear_cache_success': 'キャッシュを消去しました！ {size} 解放されました。',
      'settings_cache_info': '自動クリーンアップ有効',
      'settings_cache_info_desc': '変換完了時に一時的な動画キャッシュは自動的に削除されます。',
      'device_specs': '端末の仕様',
      'device_model': 'モデル',
      'device_soc': 'SoC / ボード',
      'device_cpu_cores': 'CPUコア数',
      'device_total_ram': '合計RAM',
      'theme_dark_desc': 'ダークネイビー (#11111B)',
      'theme_oled_desc': '完全な漆黒 (#000000) • AMOLEDの省電力',
      'theme_light_desc': 'クリーン＆ブライト (#F6F7FB)',
      'select_mode': 'モード選択',
      'mode_downscale': '縮小・圧縮',
      'mode_upscale': 'アップスケール',
      'mode_convert': 'フォーマット変換',
      'badge_soon': '近日登場',
      'target_fps': '目標フレームレート (FPS)',
      'fps_original': 'オリジナル',
      'proc_play_video': '動画を再生',
      'share': '共有',
      'close': '閉じる',
      'no_downscale_options': '動画はすでに低解像度です。\n縮小オプションはありません。',
      'proc_notif_completed': '変換完了！動画はMoviesに保存されました',
    },
    'zh_CN': {
      'desc_crf': '不考虑最终文件大小，保持恒定的视觉画质。数值越小画质越好，但文件越大。强烈推荐。',
      'desc_bitrate': '强制视频达到设定的目标文件大小 (MB)，画质将随之自动调整。',
      'desc_mp4': '轻量且兼具极致兼容性。适用于社交媒体、手机录像与分享。',
      'desc_mkv': '单文件支持多音轨与多字幕。适用于电影、动漫与连续剧收藏。',
      'desc_mov': '极高原始画质。适用于专业剪辑软件 (Premiere / FCPX)。',
      'desc_webm': '支持透明通道。适用于网页动画与流媒体内容。',
      'desc_h264': '直播、网络视频与标准录像。拥有无与伦比的极高兼容性。',
      'desc_hevc': '4K 流媒体与高清影视。超高压缩效率，可节省高达 50% 空间。',
      'desc_vp9': 'YouTube 与 Google 生态推荐。拥有超高的压缩比率。',
      'est_size_title': '预估输出大小:',
      'est_size_warning': '* 实际大小可能因画面复杂度和动态细节而有所浮动。',
      'crf_label': 'CRF 数值 (越小 = 画质越佳，体积越大)',
      'bitrate_label': '目标码率 (Mbps)',
      'app_title': 'Phantek Video Toolkit',
      'app_tagline': '轻松将 4K/2K 视频降分辨率\n并高效压缩文件大小',
      'pick_video': '选择视频',
      'change_video': '更换视频',
      'reset': '重置',
      'settings': '设置',
      'loading_pick': '正在打开文件选择器...',
      'loading_analyzing': '正在分析并读取视频信息...',
      'loading_large_hint': '大容量视频文件可能需要几秒钟完成解析。',
      'error_read_video': '读取视频信息失败',
      'source_video': '原视频',
      'resolution': '分辨率',
      'duration': '时长',
      'bitrate': '码率',
      'file_size': '大小',
      'fps': '帧率',
      'codec': '编码格式',
      'format': '封装格式',
      'target_resolution': '目标分辨率',
      'original_resolution': '原分辨率 (保持不变)',
      'video_already_low': '视频分辨率已经较低',
      'can_still_compress': '您依然可以压缩码率或转换封装/编码格式。',
      'video_options': '视频与压缩设置',
      'bitrate_setting': '目标码率',
      'container_format': '文件格式',
      'video_codec': '视频编码',
      'start_conversion': '开始转换',
      'feature_downscale': '4K → 1080p',
      'feature_fast': '快速',
      'feature_quality': '高画质',
      'feature_offline': '100% 离线',
      'settings_title': '应用设置',
      'settings_language': '语言 (Language)',
      'settings_language_desc': '选择应用界面的显示语言。',
      'settings_theme': '主题外观',
      'settings_theme_desc': '在标准暗色模式、适用于 AMOLED 屏幕省电的 OLED 纯黑模式或浅色亮色模式之间切换。',
      'theme_dark': '深色模式',
      'theme_oled': 'OLED 纯黑',
      'theme_light': '浅色模式',
      'settings_wakelock': '保持屏幕常亮',
      'settings_wakelock_desc': '在应用运行或转码视频时防止手机息屏休眠。⚠️ 警告：开启此功能会加快电池电量消耗。',
      'settings_hardware': '硬件与性能设置',
      'settings_cpu_threads': 'CPU 核心 / 线程数',
      'settings_cpu_threads_desc': '设置转码使用的线程数。核心越多转码越快，但发热与耗电会相应增加。',
      'settings_detected_cores': '检测到当前设备拥有 {count} 个 CPU 核心',
      'settings_auto_cores': '自动 (调用全部核心)',
      'settings_ram_buffer': 'RAM 运行内存与缓存上限',
      'settings_ram_buffer_desc': '调整 FFmpeg 内存缓存池大小，防止小内存手机闪退 (OOM)。',
      'settings_ram_low': '256 MB (省内存模式)',
      'settings_ram_standard': '512 MB (标准均衡)',
      'settings_ram_high': '1024 MB (高性能)',
      'settings_ram_max': '2048 MB (极速最大)',
      'settings_cpu_preset': 'CPU 编码速度预设 (Preset)',
      'settings_cpu_preset_desc': 'Fast：极速处理（少压缩）；Normal：速度与画质均衡；Slow：最大压缩（较慢）。',
      'preset_fast': 'Fast (少压缩/极速)',
      'preset_normal': 'Normal (均衡)',
      'preset_slow': 'Slow (最大压缩)',
      'settings_hw_accel': '硬件加速 (实验性)',
      'settings_hw_accel_desc': '启用 Android MediaCodec 芯片硬件加速，更低功耗转码。',
      'settings_audio_quality': '音频质量 (码率)',
      'settings_audio_quality_desc': '设置输出 AAC 音频码率，或选择静音移除音轨以进一步减小文件体积。',
      'settings_audio_mute': '静音 (移除音频)',
      'settings_reset_default': '恢复默认设置',
      'settings_reset_confirm_title': '恢复默认设置？',
      'settings_reset_confirm_desc': '确定要将所有配置项恢复为初始默认值吗？',
      'settings_reset_success': '已成功恢复默认设置',
      'settings_about': '关于应用',
      'settings_about_desc': 'Phantek Video Toolkit 是一款完全离线运行的移动端视频转码压缩工具，保障您的绝对隐私。',
      'bitrate_auto': '自动 (推荐计算)',
      'bitrate_high': '高画质',
      'bitrate_medium': '均衡',
      'bitrate_low': '极速省空间 (最小文件)',
      'bitrate_custom': '自定义 ({value} kbps)',
      'proc_title': '转码处理中',
      'proc_preparing': '正在准备转换...',
      'proc_converting': '正在转码视频...',
      'proc_completed': '转码完成！',
      'proc_failed': '转码失败',
      'proc_open_file': '打开视频文件',
      'proc_back': '返回',
      'proc_retry': '重试',
      'proc_cancel': '取消',
      'proc_cancel_title': '中止转码？',
      'proc_cancel_desc': '转码任务正在进行中，确认要中断并取消吗？',
      'proc_yes_cancel': '确认取消',
      'proc_no': '继续运行',
      'proc_source': '原视频',
      'proc_target': '目标视频',
      'proc_output_size': '输出文件大小',
      'proc_savings': '节省空间 {percent}%',
      'proc_size_increase': '体积 +{percent}%',
      'proc_savings_title': '节省空间: {percent}%',
      'proc_size_increase_title': '文件体积增加: +{percent}%',
      'proc_size_increase_hint': '为了保留最高视觉画质，转换后的文件体积大于原始视频。',
      'proc_elapsed_time': '已耗时',
      'proc_remaining_time': '预计剩余',
      'proc_calculating': '正在计算...',
      'proc_total_time': '总耗时: {time}',
      'proc_saved_location': '存储文件夹',
      'proc_saved_path': 'Movies',
      'settings_storage': '存储与缓存管理',
      'settings_storage_desc': '清理临时缓存文件，防止应用占用过多存储空间。',
      'settings_cache_size': '当前缓存大小',
      'settings_clear_cache': '立即清理缓存',
      'settings_clear_cache_success': '缓存已清理完毕！已释放 {size} 空间。',
      'settings_cache_info': '自动清理已启用',
      'settings_cache_info_desc': '转码完成后会自动删除临时视频文件，防止体积膨胀。',
      'device_specs': '设备规格',
      'device_model': '型号',
      'device_soc': 'SoC / 主板',
      'device_cpu_cores': 'CPU 核心数',
      'device_total_ram': '总运行内存 (RAM)',
      'theme_dark_desc': '深海暗灰 (#11111B)',
      'theme_oled_desc': '纯黑 (#000000) • AMOLED 极度省电',
      'theme_light_desc': '明亮清晰 (#F6F7FB)',
      'select_mode': '选择模式',
      'mode_downscale': '压缩降级',
      'mode_upscale': '超分辨率放大',
      'mode_convert': '格式转换',
      'badge_soon': '即将推出',
      'target_fps': '目标帧率 (FPS)',
      'fps_original': '原始帧率',
      'proc_play_video': '播放视频',
      'share': '分享',
      'close': '关闭',
      'no_downscale_options': '视频已经是低分辨率。\n没有适用的降分辨率选项。',
      'proc_notif_completed': '转换完成！视频已保存至 Movies',
    },
    'zh_TW': {
      'desc_crf': '不論最終檔案大小，保持穩定的畫質表現。數值越小畫質越好，但檔案越大。強烈推薦。',
      'desc_bitrate': '強制影片達到設定的目標大小 (MB)，畫質將自動配合調整。',
      'desc_mp4': '輕巧且具備極佳相容性。適合社群媒體、手機拍攝與影片分享。',
      'desc_mkv': '單一檔案容納多音軌與多字幕。適合收藏電影、動畫與電視影集。',
      'desc_mov': '超高原始畫質。適合專業剪輯軟體 (Premiere / FCPX)。',
      'desc_webm': '支援透明通道。適合網頁動態特效與網路串流內容。',
      'desc_h264': '直播串流、網路影片與標準拍攝。擁有極度廣泛的相容度。',
      'desc_hevc': '4K 串流與高畫質影視。極致壓縮效率，容量最高節省 50%。',
      'desc_vp9': 'YouTube 與 Google 產品廣泛採用。壓縮效能極為出眾。',
      'est_size_title': '預估輸出大小:',
      'est_size_warning': '* 實際大小可能因畫面複雜度與動態場景而略有差異。',
      'crf_label': 'CRF 數值 (數值越小 = 畫質越佳，體積越大)',
      'bitrate_label': '目標位元率 (Mbps)',
      'app_title': 'Phantek Video Toolkit',
      'app_tagline': '輕鬆將 4K/2K 影片降解析度\n並高效壓縮檔案大小',
      'pick_video': '選取影片',
      'change_video': '更換影片',
      'reset': '重設',
      'settings': '設定',
      'loading_pick': '正在開啟檔案選取器...',
      'loading_analyzing': '正在分析並讀取影片資訊...',
      'loading_large_hint': '大容量影片檔案可能需要數秒時間完成解析。',
      'error_read_video': '讀取影片資訊失敗',
      'source_video': '原始影片',
      'resolution': '解析度',
      'duration': '長度',
      'bitrate': '位元率',
      'file_size': '大小',
      'fps': '影格率 (FPS)',
      'codec': '編碼格式',
      'format': '封裝格式',
      'target_resolution': '目標解析度',
      'original_resolution': '原解析度 (維持不變)',
      'video_already_low': '影片解析度已經較低',
      'can_still_compress': '您依然可以壓縮位元率或轉換封裝/編碼格式。',
      'video_options': '影片與壓縮設定',
      'bitrate_setting': '目標位元率',
      'container_format': '檔案格式',
      'video_codec': '視訊編碼',
      'start_conversion': '開始轉換',
      'feature_downscale': '4K → 1080p',
      'feature_fast': '快速',
      'feature_quality': '高畫質',
      'feature_offline': '100% 離線',
      'settings_title': '應用程式設定',
      'settings_language': '語言 (Language)',
      'settings_language_desc': '選取應用程式介面的顯示語言。',
      'settings_theme': '主題外觀',
      'settings_theme_desc': '在標準深色模式、適用於 AMOLED 螢幕省電的 OLED 純黑模式或淺色明亮模式之間切換。',
      'theme_dark': '深色模式',
      'theme_oled': 'OLED 純黑',
      'theme_light': '淺色模式',
      'settings_wakelock': '保持螢幕常亮',
      'settings_wakelock_desc': '在應用程式執行或轉檔影片時防止手機休眠關閉螢幕。⚠️ 警告：開啟此功能將會加快電池電量消耗。',
      'settings_hardware': '硬體與效能設定',
      'settings_cpu_threads': 'CPU 核心 / 執行緒數',
      'settings_cpu_threads_desc': '設定轉檔使用的執行緒數量。核心越多轉檔越快，但耗電與發熱會增加。',
      'settings_detected_cores': '偵測到本裝置具備 {count} 個 CPU 核心',
      'settings_auto_cores': '自動 (調用全部核心)',
      'settings_ram_buffer': 'RAM 記憶體與快取上限',
      'settings_ram_buffer_desc': '調整 FFmpeg 記憶體快取大小，避免記憶體不足 (OOM) 導致閃退。',
      'settings_ram_low': '256 MB (省記憶體模式)',
      'settings_ram_standard': '512 MB (標準平衡)',
      'settings_ram_high': '1024 MB (高效能)',
      'settings_ram_max': '2048 MB (最大極限)',
      'settings_cpu_preset': 'CPU 編碼速度預設 (Preset)',
      'settings_cpu_preset_desc': 'Fast：極速處理（少壓縮）；Normal：速度與畫質均衡；Slow：最大壓縮（較慢）。',
      'preset_fast': 'Fast (少壓縮/極速)',
      'preset_normal': 'Normal (均衡)',
      'preset_slow': 'Slow (最大壓縮)',
      'settings_hw_accel': '硬體加速 (實驗性)',
      'settings_hw_accel_desc': '啟用 Android MediaCodec 晶片硬體加速，享受更低功耗轉檔。',
      'settings_audio_quality': '音訊品質 (位元率)',
      'settings_audio_quality_desc': '設定輸出 AAC 音訊位元率，或選取靜音移除音軌以進一步縮小檔案大小。',
      'settings_audio_mute': '靜音 (移除音軌)',
      'settings_reset_default': '還原預設設定',
      'settings_reset_confirm_title': '還原預設設定？',
      'settings_reset_confirm_desc': '確定要將所有偏好設定恢復為原廠預設值嗎？',
      'settings_reset_success': '已成功恢復預設設定',
      'settings_about': '關於應用程式',
      'settings_about_desc': 'Phantek Video Toolkit 是一款完全離線執行的行動端影片轉檔壓縮工具，全力保護您的隱私。',
      'bitrate_auto': '自動 (推薦計算)',
      'bitrate_high': '高畫質',
      'bitrate_medium': '平衡',
      'bitrate_low': '節省空間 (最小檔案)',
      'bitrate_custom': '自訂 ({value} kbps)',
      'proc_title': '轉檔處理中',
      'proc_preparing': '正在準備轉換...',
      'proc_converting': '正在轉檔影片...',
      'proc_completed': '轉檔完成！',
      'proc_failed': '轉檔失敗',
      'proc_open_file': '開啟影片檔案',
      'proc_back': '返回',
      'proc_retry': '重試',
      'proc_cancel': '取消',
      'proc_cancel_title': '中止轉檔？',
      'proc_cancel_desc': '轉檔作業正在進行中，確定要中途取消嗎？',
      'proc_yes_cancel': '確定取消',
      'proc_no': '繼續轉檔',
      'proc_source': '原始影片',
      'proc_target': '目標影片',
      'proc_output_size': '輸出檔案大小',
      'proc_savings': '節省空間 {percent}%',
      'proc_size_increase': '容量 +{percent}%',
      'proc_savings_title': '節省空間: {percent}%',
      'proc_size_increase_title': '檔案容量增加: +{percent}%',
      'proc_size_increase_hint': '為了保留最高視覺畫質，轉換後的檔案容量大於原始影片。',
      'proc_elapsed_time': '已耗时',
      'proc_remaining_time': '預計剩餘',
      'proc_calculating': '正在計算...',
      'proc_total_time': '總耗時: {time}',
      'proc_saved_location': '儲存資料夾',
      'proc_saved_path': 'Movies',
      'settings_storage': '儲存與快取管理',
      'settings_storage_desc': '清理暫存快取檔案，避免應用程式佔用過多儲存空間。',
      'settings_cache_size': '目前快取大小',
      'settings_clear_cache': '立即清理快取',
      'settings_clear_cache_success': '快取已清理完成！已釋放 {size} 空間。',
      'settings_cache_info': '自動清理已啟用',
      'settings_cache_info_desc': '轉檔完成後會自動刪除暫存影片檔案，防止體積膨脹。',
      'device_specs': '裝置規格',
      'device_model': '型號',
      'device_soc': 'SoC / 主機板',
      'device_cpu_cores': 'CPU 核心數',
      'device_total_ram': '總記憶體 (RAM)',
      'theme_dark_desc': '深海暗灰 (#11111B)',
      'theme_oled_desc': '純黑 (#000000) • AMOLED 極度省電',
      'theme_light_desc': '明亮清晰 (#F6F7FB)',
      'select_mode': '選擇模式',
      'mode_downscale': '壓縮降解析度',
      'mode_upscale': '超解析度放大',
      'mode_convert': '格式轉換',
      'badge_soon': '即將推出',
      'target_fps': '目標幀率 (FPS)',
      'fps_original': '原始幀率',
      'proc_play_video': '播放影片',
      'share': '分享',
      'close': '關閉',
      'no_downscale_options': '影片已是低解析度。\n無適用的降解析度選項。',
      'proc_notif_completed': '轉換完成！影片已儲存至 Movies',
    },
    'ko': {
      'desc_crf': '최종 파일 크기에 구애받지 않고 일관된 화질을 유지합니다. 값이 낮을수록 고화질이지만 용량이 커집니다. 가장 추천하는 방식입니다.',
      'desc_bitrate': '정확한 목표 용량(MB)에 맞추어 인코딩하며, 화질은 그에 맞게 자동 조절됩니다.',
      'desc_mp4': '가볍고 호환성이 가장 뛰어남. 소셜 미디어, 스마트폰 영상 촬영 및 공유에 최적.',
      'desc_mkv': '하나의 파일에 여러 오디오와 자막 수납 가능. 영화, 애니메이션, 드라마 보관용.',
      'desc_mov': '고화질 원본 품질 유지. 전문 영상 편집 프로그램(Premiere/FCPX)에 최적.',
      'desc_webm': '투명 배경 동영상 지원. 웹 애니메이션 및 온라인 스트리밍용.',
      'desc_h264': '라이브 스트리밍, 웹 동영상, 표준 스마트폰 녹화. 최고의 범용 호환성.',
      'desc_hevc': '4K 스트리밍, 고화질 영화. 최대 50% 용량을 절약하는 최고 수준의 압축 효율.',
      'desc_vp9': 'YouTube 및 Google 제품군 표준. 매우 우수한 압축 효율.',
      'est_size_title': '예상 출력 크기:',
      'est_size_warning': '* 실제 크기는 동영상의 시각적 복잡도에 따라 달라질 수 있습니다.',
      'crf_label': 'CRF 값 (낮을수록 = 더 높은 화질, 큰 용량)',
      'bitrate_label': '목표 비트레이트 (Mbps)',
      'app_title': 'Phantek Video Toolkit',
      'app_tagline': '4K/2K 고해상도 동영상을\n화질 손실 없이 손쉽게 압축하세요',
      'pick_video': '동영상 선택',
      'change_video': '동영상 변경',
      'reset': '초기화',
      'settings': '설정',
      'loading_pick': '파일 탐색기 여는 중...',
      'loading_analyzing': '동영상 정보 및 메타데이터 분석 중...',
      'loading_large_hint': '대용량 파일은 분석에 수 초가 걸릴 수 있습니다.',
      'error_read_video': '동영상 정보를 읽는데 실패했습니다',
      'source_video': '원본 동영상',
      'resolution': '해상도',
      'duration': '재생 시간',
      'bitrate': '비트레이트',
      'file_size': '파일 크기',
      'fps': '프레임레이트',
      'codec': '코덱',
      'format': '형식',
      'target_resolution': '목표 해상도',
      'original_resolution': '원본 해상도 유지',
      'video_already_low': '이미 낮은 해상도의 동영상입니다',
      'can_still_compress': '비트레이트를 낮추거나 형식/코덱을 변경하여 압축할 수 있습니다.',
      'video_options': '동영상 및 압축 옵션',
      'bitrate_setting': '목표 비트레이트',
      'container_format': '파일 형식',
      'video_codec': '비디오 코덱',
      'start_conversion': '변환 시작',
      'feature_downscale': '4K → 1080p',
      'feature_fast': '빠른 속도',
      'feature_quality': '고화질',
      'feature_offline': '100% 오프라인',
      'settings_title': '설정',
      'settings_language': '언어 (Language)',
      'settings_language_desc': '앱 인터페이스 표시 언어를 선택하세요.',
      'settings_theme': '화면 테마',
      'settings_theme_desc': '표준 다크 모드, AMOLED 화면에서 배터리를 절약하는 OLED 다크 모드, 또는 라이트 모드 중에서 선택하세요.',
      'theme_dark': '다크 모드',
      'theme_oled': '다크 OLED',
      'theme_light': '라이트 모드',
      'settings_wakelock': '화면 켜짐 유지',
      'settings_wakelock_desc': '동영상 인코딩 중이나 앱 사용 중에 화면이 꺼지거나 절전 모드로 들어가는 것을 방지합니다. ⚠️ 경고: 배터리가 더 빠르게 소모될 수 있습니다.',
      'settings_hardware': '하드웨어 및 성능 설정',
      'settings_cpu_threads': 'CPU 코어 / 스레드 수',
      'settings_cpu_threads_desc': '인코딩에 사용할 CPU 스레드 수를 설정합니다. 코어가 많을수록 변환이 빨라집니다.',
      'settings_detected_cores': '이 기기에서 {count}개의 CPU 코어가 감지됨',
      'settings_auto_cores': '자동 (모든 코어 사용)',
      'settings_ram_buffer': 'RAM 및 메모리 버퍼 한도',
      'settings_ram_buffer_desc': '메모리 부족(OOM) 방지를 위한 FFmpeg 캐시 버퍼 용량을 설정합니다.',
      'settings_ram_low': '256 MB (메모리 절약)',
      'settings_ram_standard': '512 MB (표준 균형)',
      'settings_ram_high': '1024 MB (고성능)',
      'settings_ram_max': '2048 MB (최대 용량)',
      'settings_cpu_preset': 'CPU 인코딩 속도 프리셋',
      'settings_cpu_preset_desc': 'Fast: 빠른 변환(최소 압축); Normal: 균형 모드; Slow: 최대 압축(느림).',
      'preset_fast': 'Fast (최소 압축/빠름)',
      'preset_normal': 'Normal (균형)',
      'preset_slow': 'Slow (최대 압축)',
      'settings_hw_accel': '하드웨어 가속 (실험적 기능)',
      'settings_hw_accel_desc': '기기가 지원하는 경우 Android MediaCodec을 통해 저전력으로 인코딩합니다.',
      'settings_audio_quality': '오디오 품질 (비트레이트)',
      'settings_audio_quality_desc': '출력 AAC 오디오 비트레이트를 설정하거나 음소거를 선택하여 오디오를 제거하고 용량을 줄입니다.',
      'settings_audio_mute': '음소거 (소리 없음)',
      'settings_reset_default': '기본값으로 재설정',
      'settings_reset_confirm_title': '설정을 재설정하시겠습니까?',
      'settings_reset_confirm_desc': '모든 사용자 설정을 기본값으로 되돌리시겠습니까?',
      'settings_reset_success': '설정이 기본값으로 재설정되었습니다',
      'settings_about': '앱 정보',
      'settings_about_desc': 'Phantek Video Toolkit는 외부 서버 업로드 없이 기기 내에서 100% 안전하게 동작하는 오프라인 동영상 압축 도구입니다.',
      'bitrate_auto': '자동 (최적 계산)',
      'bitrate_high': '고화질',
      'bitrate_medium': '균형',
      'bitrate_low': '용량 절약 (최소 크기)',
      'bitrate_custom': '사용자 지정 ({value} kbps)',
      'proc_title': '변환 진행 중',
      'proc_preparing': '변환 준비 중...',
      'proc_converting': '동영상 변환 중...',
      'proc_completed': '변환 완료!',
      'proc_failed': '동영상 변환 실패',
      'proc_open_file': '동영상 파일 열기',
      'proc_back': '돌아가기',
      'proc_retry': '다시 시도',
      'proc_cancel': '취소',
      'proc_cancel_title': '변환을 취소하시겠습니까?',
      'proc_cancel_desc': '동영상 인코딩이 진행 중입니다. 정말 취소하시겠습니까?',
      'proc_yes_cancel': '예, 취소합니다',
      'proc_no': '계속 진행',
      'proc_source': '원본',
      'proc_target': '변환 후',
      'proc_output_size': '출력 크기',
      'proc_savings': '{percent}% 절약됨',
      'proc_size_increase': '크기 +{percent}%',
      'proc_savings_title': '저장 공간 절약: {percent}%',
      'proc_size_increase_title': '파일 용량 증가: +{percent}%',
      'proc_size_increase_hint': '최고의 화질을 유지하기 위해 변환된 파일 용량이 원본 동영상보다 큽니다.',
      'proc_elapsed_time': '진행 시간',
      'proc_remaining_time': '예상 남은 시간',
      'proc_calculating': '계산 중...',
      'proc_total_time': '총 소요 시간: {time}',
      'proc_saved_location': '저장 폴더',
      'proc_saved_path': 'Movies',
      'settings_storage': '저장 공간 및 캐시',
      'settings_storage_desc': '임시 캐시 파일을 관리하여 저장 공간 낭비를 방지합니다.',
      'settings_cache_size': '현재 캐시 크기',
      'settings_clear_cache': '지금 캐시 삭제',
      'settings_clear_cache_success': '캐시가 삭제되었습니다! {size} 공간 확보됨.',
      'settings_cache_info': '자동 정리 활성화됨',
      'settings_cache_info_desc': '변환이 완료되면 임시 동영상 파일이 자동으로 삭제됩니다.',
      'device_specs': '기기 사양',
      'device_model': '모델',
      'device_soc': 'SoC / 보드',
      'device_cpu_cores': 'CPU 코어 수',
      'device_total_ram': '총 RAM',
      'theme_dark_desc': '네이비 / 슬레이트 다크 (#11111B)',
      'theme_oled_desc': '트루 블랙 (#000000) • AMOLED 배터리 절약',
      'theme_light_desc': '밝고 선명함 (#F6F7FB)',
      'select_mode': '모드 선택',
      'mode_downscale': '해상도 축소',
      'mode_upscale': '해상도 확대',
      'mode_convert': '포맷 변환',
      'badge_soon': '출시 예정',
      'target_fps': '목표 프레임 (FPS)',
      'fps_original': '원본',
      'proc_play_video': '동영상 재생',
      'share': '공유',
      'close': '닫기',
      'no_downscale_options': '동영상이 이미 저해상도입니다.\n사용 가능한 축소 옵션이 없습니다.',
      'proc_notif_completed': '변환 완료! 동영상이 Movies에 저장되었습니다',
    },
  };

  String t(String key, {Map<String, String>? args}) {
    final langValues = _localizedValues[languageCode] ?? _localizedValues['en'] ?? {};
    String value = langValues[key] ?? _localizedValues['en']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}
